### ISSUE TITLE
[FEATURE] Custom Contact Fields

### ISSUE THREAD

**Issue by HeidiChristy** [leviFrosty/jw-time#103]
Would like the option of one or two customizable fields in contact info to add personalized data ie.: Religion, Family Members name, pet etc

this would be easily seen each time you looked at the contact and keep you from having to scroll through long notes.  

⭐️ like the simple clean format!  Easy to use

💡 would be nice to be able to customize the font size as it’s currently quite small.  My ageing eyes struggle with the default size.

**Comment by leviFrosty** [comment]
Hello @HeidiChristy!

Thanks for writing in, I appreciate the kind words. 

Regarding custom fields, this is something that I will add. Unfortunately, it may be some time before the feature is released, but I will do my best to keep you in the loop once the feature is complete.

As far as font sizes, I think I can understand your concern. System font preferences will affect JW Time's display size, but having the ability to further override would be useful. I will add a small feature in the settings that will add an additional font size offset - separate from system settings.

Thank you for using and sharing JW Time with others!

Best,
Levi

**Comment by leviFrosty** [comment]
Hello @HeidiChristy !

Good news! The font size feature you requested has been added as part of 2487d283296b4fb2c7f32f9d85e182eafc0da46e

Thanks for writing in. Your other feature request will eventually be added in the near future.

Best,
Levi

**Comment by leviFrosty** [comment]
@HeidiChristy 

Good news again! The custom fields feature has been added as part of 980fb6117240239bb785844fd2376fa3d22ad73a

Take care. I hope you enjoy the app and the coming features and improvements. Please share JW Time with friends and family.

I'll be closing this ticket. Let me know if you have any questions, comments, or concerns in the future.

Best,
Levi
