### ISSUE TITLE
[FEATURE] Delete Single Occurrence of Recurring Schedule

### ISSUE THREAD

**Issue by Krisie17** [leviFrosty/jw-time#105]
hello, I just noticed the new update for planning our month ahead of time which is great. I love that idea and I’m so happy you added it. One note is that it would be nice if for certain days that we already have reoccurring plans but we’re going away or can’t go out in service that day if it would be nice to be able to cancel out plans for certain days, or put in an empty day without ruining our reoccurring schedule going forward. If you could fix that, that would be awesome. 

I tried going in and just adding a daily plan And saying zero, but it doesn’t let you put in anything less than five minutes and if I do that, I’m going to start messing up my time by five minute increments because it’s inaccurate

**Comment by leviFrosty** [comment]
@Krisie17 

I'm happy to let you know this feature has been implemented as of 88d3672a2286e2253f1a0ab985ad4bf74512717d

Expect to see it in the coming release.

I'll be closing this ticket now. Please let me know if you have any questions or comments once you get your hands on it.

Thank you,
Levi
