### ISSUE TITLE
[FEATURE] Timer

### ISSUE THREAD

**Issue by dougdsm** [leviFrosty/jw-time#111]
The app is great, light and simple. But, i miss a timer, it would be a good feature for the next version.
Tks brother

**Comment by leviFrosty** [comment]
@dougdsm 

Thanks for writing in and I appreciate the kind words. A timer feature is already underway. See: #108

I will let you know when this feature has been implemented. 

Thanks for enjoying the app and let me know if you have any questions or comments in the future.

Best,
Levi

**Comment by leviFrosty** [comment]
@dougdsm

Fantastic news! This feature has been implemented as part of ec73427accd84fa4f8a1c7174a7d6551d3d78647

Expect it in the upcoming update. 

I hope you continue to enjoy the app. I'll be closing this issue now, let me know if you have any questions or concerns once you have your hands on the feature.

Best,
Levi
