### ISSUE TITLE
[FEATURE] Actual Time vs Planned

### ISSUE THREAD

**Issue by flossyk1** [leviFrosty/jw-time#113]
**Is your feature request related to a problem? Please describe.*
Unsure how much time ive got in vs predicted 

**Describe the solution you'd like**
If possible would be good to see on the main page the scheduled hours combined with actual so you know if you're anywhere close or need to work a bit harder!

**Additional context**

**Comment by leviFrosty** [comment]
Hello again @flossyk1 !

Thanks for the ticket. Apologies for the delayed response.

I will be working on this feature and will keep you in the loop.

Thanks,
Levi

**Comment by leviFrosty** [comment]
@flossyk1 

Good news! This feature has been implemented in 5213cbb9523da883b786fe03055063e5823f72ed. Expect to see it in the coming release.

Thanks for patiently waiting - I've been extremely busy recently with my day job.

Best,
Levi
