### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Danrico95** [leviFrosty/jw-time#114]
Bug: 
Anytime I try to go into any of my newly created Return Visits, it closes the app completely. It also does this when adding a new return visit, once I finalize all the details. 

**To Reproduce**
Open the App
Scroll down to Return Visits
Tap on any of the return visits I have created

**Expected behavior**

I expected to be able to open up my return visits and see what details I added, be able to edit any details and also do the same with planned visits. 

**Screenshots**
If applicable, add screenshots to help explain your problem. (Draw on images if possible)

https://github.com/leviFrosty/jw-time/assets/168923274/19ea3ae1-5c2f-4dfb-8a7d-f13feb1c282e

**Smartphone (please complete the following information):**

- Device: iPhone 13 Pro Max
- OS: iOS 17.4.1
- Version 1.26.2

**Additional context**

**Comment by leviFrosty** [comment]
Hi,

I'm sorry you're experiencing this issue. While I work on reproducing this, will you please go to your settings > backup. > create backup.


What app version are you on? The notes say 1.26.2, but this version does not exist.

After you check the app version, reinstall and then restore from your backup.

If this still does not resolve your issue, please email me at support@leviwilkerson.com so we can have a diagnostic session where we can get a bit more specific.

Thanks for your help, I hope we can get this resolved for you.

Regardless, I'm looking into this issue on my end as well.

Best,
Levi

**Comment by leviFrosty** [comment]
@Danrico95 

Thanks for working with me to get this resolved.

I am closing this ticket as this was resolved with: 14d9bb2c0ba1dbf2b208328271d0eaa9543c032d

Best,
Levi
