### ISSUE TITLE
[LDC hours should be included in time since they are credited to the hours you have]

### ISSUE THREAD

**Issue by JephCarla** [leviFrosty/jw-time#124]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by leviFrosty** [comment]
Hi @JephCarla,

Thanks for writing in! I hope you are enjoying your experience using JW Time.

LDC hours are included in your hour total for the month.
![IMG_7623](https://github.com/leviFrosty/jw-time/assets/79994715/f0314af7-3c7a-4336-a7eb-3a9a69e64a40)

If you're referring to the service-year total, the calculation uses up to 55 hours for a given month of LDC time (credit hours) in accordance with the branch's hour limits.

If this doesn't answer your question, please let me know and we can resolve any issues / concerns you may have. For now I will close this ticket.

Best,
Levi

**Comment by JephCarla** [comment]
All my hours equal 735..
But the app says I only have 532 hours. I hope this helps you to understand what I mean.

Carla Addiah
314-715-4698
________________________________
