### ISSUE TITLE
[BUG] Annual Hours Incorrectly Calculated

### ISSUE THREAD

**Issue by JephCarla** [leviFrosty/jw-time#125]
All my hours equal 735..
But the app says I only have 532 hours. I hope this helps you to understand what I mean.

![IMG_5284](https://github.com/leviFrosty/jw-time/assets/174302892/a39f75e7-b065-40ed-bd21-623af65d6d73)
![IMG_5287](https://github.com/leviFrosty/jw-time/assets/174302892/6714a18a-3ff9-4c5c-948c-54efad928811)
![IMG_5286](https://github.com/leviFrosty/jw-time/assets/174302892/7e07d0eb-a770-414d-b0b4-20af4fa73300)
![IMG_5285](https://github.com/leviFrosty/jw-time/assets/174302892/e69c37a2-1101-4b5c-a7d8-b1a3d208b70d)
![IMG_5288](https://github.com/leviFrosty/jw-time/assets/174302892/e91c430a-d3a5-4b3b-8924-4de8064171a7)
![IMG_5289](https://github.com/leviFrosty/jw-time/assets/174302892/0a0aea76-9738-40f9-818c-23266498ae03)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. (Draw on images if possible)

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone 15 Pro Max]
- OS: [e.g. iOS 17.1.2]
- Version [e.g. 1.9.0]

**Additional context**

**Comment by leviFrosty** [comment]
@JephCarla 

Thank you for reporting this. I will be working to get this resolved as quickly as possible.

This is a high priority issue.

Best,
Levi

**Comment by leviFrosty** [comment]
@JephCarla 

Are you available tonight for a WhatsApp phone call to help with diagnosing this issue?

Please call me: +15023348618

I need further information.

Thanks,
Levi

**Comment by JephCarla** [comment]
I really appreciate all you have done with the app. I must apologize, but at the moment I live a busy schedule and don't have time for a call. I have to download something that's simple and that will assist me with my busy daily schedule. I'm confident that you will figure this out. Thanks so much for everything.
