### ISSUE TITLE
[BUG] Annual Hours Incorrectly Calculated

### ISSUE THREAD

**Issue by Mebradford** [leviFrosty/jw-time#126]
**Describe the bug**
The total hours for the year are not calculated correctly. 

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. (Draw on images if possible)

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone 15 Pro Max] yes
- OS: [e.g. iOS 17.1.2] 17.6.2 unknown
![IMG_1626](https://github.com/leviFrosty/jw-time/assets/174878603/55a915f1-5b65-48bb-9810-34f7d530a7b9)

- Version [e.g. 1.9.0]

**Additional context**

**Comment by leviFrosty** [comment]
@Mebradford 

Thank you for reporting this. I will be working to get this resolved as quickly as possible.

This is a high priority issue.

Best,
Levi

**Comment by leviFrosty** [comment]
@Mebradford 

Are you available tonight for a WhatsApp phone call to help with diagnosing this issue?

Please call me: +15023348618

I need further information.

Thanks,
Levi

**Comment by Mebradford** [comment]
Hello. I am sorry I am just seeing your message. I am on East Coast Time in the US. I have time during the day tomorrow from 11 am on. Sincerely,Melanie BradfordOn Jul 8, 2024, at 6:49 PM, Levi Wilkerson ***@***.***> wrote:﻿
@Mebradford
Are you available tonight for a WhatsApp phone call to help with diagnosing this issue?
Please call me: +15023348618
I need further information.
Thanks,
Levi

**Comment by leviFrosty** [comment]
No problem. I'm available tomorrow at 11am. I'm also EST.

Give me a call then.

Thanks,
Levi

**Comment by leviFrosty** [comment]
@Mebradford 

Hey, didn't receive a call from you this morning. No worries, feel free to give me a call until 5:30pm EST today.

Best,
Levi

**Comment by leviFrosty** [comment]
@Mebradford 

Please give me a call whenever you're available at: +15023348618

If I'm not available, I'll send you a message in reply and we can work out a time to support.

Best,
Levi

**Comment by leviFrosty** [comment]
@Mebradford

Because I have been unable to replicate this issue and it has become stale, I will be closing this issue.

Feel free to reply to this email/message to continue the conversation. I will be available.

Best,
Levi
