### ISSUE TITLE
[錯誤]

### ISSUE THREAD

**Issue by DAIANYI77** [leviFrosty/jw-time#132]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. (Draw on images if possible)

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone 15 Pro Max]
- OS: [e.g. iOS 17.1.2]
- Version [e.g. 1.9.0]

**Additional context**

**Comment by DAIANYI77** [comment]
The language is gone.English only

**Comment by leviFrosty** [comment]
@DAIANYI77 

感谢您通知我！我为这个问题道歉。

我正在努力尽快解决这个问题。

谢谢，
Levi

---

Thank you for notifying me! I apologize for the problem.

I am working to get this resolved as soon as possible.

Thank you,
Levi

**Comment by leviFrosty** [comment]
@DAIANYI77

该应用已通过无线方式更新，请打开您的应用。请确保您已连接到互联网，单击“设置”->“检查更新”

该应用应重新加载。

如果这不起作用，请打开您的应用约一分钟，然后强制关闭它。它应该重新启动，中文将像以前一样工作。

如果这有效，请告诉我。

祝好，
Levi

---

The app has been updated over the air, please open your app. Please ensure you are connected to the internet, click Settings -> Check for Update

The app should reload.

If that does not work, please open your app for about a minute then force close it. It should restart with Chinese working as before.

Please let me know if this works.

Best,
Levi

**Comment by DAIANYI77** [comment]
可以囉謝謝

Taiwan +886 908377913

*戴安毅** Tai Anyi*

***@***.***



從 Windows 11  的郵件 <https://go.microsoft.com/fwlink/?LinkId=550986> 傳送


Levi Wilkerson ***@***.***>於 2024年7月20日 週六，上午9:45寫道：
