### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by complymo13** [leviFrosty/jw-time#133]
**Describe the bug**
If you tap the service report view, the app will go out, and the service report view won't go in.

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. (Draw on images if possible)

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone 15 Pro Max]
- OS: [e.g. iOS 17.1.2]
- Version [e.g. 1.9.0]

**Additional context**

**Comment by leviFrosty** [comment]
@complymo13 

Hi. 

It looks like your bug submission got cut off or did not send with details.

Please reply to this email if you still have an issue.

Best,
Levi
