### ISSUE TITLE
[FEATURE] Schedule Screen Shows Annual Total

### ISSUE THREAD

**Issue by 22JNH** [leviFrosty/jw-time#135]
It should be a new section that shows the total hours for all months' plans summed compared to goal.

![image](https://github.com/user-attachments/assets/3be3178f-c266-4400-8033-444fc302c061)

**Comment by leviFrosty** [comment]
Hi,

This feature has been implement with 320356644f1d0529441c4e620fb7e30b5a38260b

It will be available in the next release.

Thank you,
Levi
