### ISSUE TITLE
[BUG] Time away for special pioneers 

### ISSUE THREAD

**Issue by rrleandro91** [leviFrosty/jw-time#136]
**Describe the bug**
My time away is counted with the service time.

**To Reproduce**
When I add the time away, it is combined with the service time.

**Expected behavior**
"I would like my time away not to be counted with my service time. When I send my service report, I would like to include a description of my time away like a credit."

**Screenshots**
If applicable, add screenshots to help explain your problem. (Draw on images if possible)

**Smartphone (please complete the following information):** 

- Device: IPhone 14
- OS: iOS 17.5.1
- Version [e.g. 1.9.0]

**Additional context**
I'm a special pioneer and we can’t count our time away. When we report that time, we receive a credit. For example, if I take one day off, I'll get 4 hours of credit. If it’s two days, I'll get 8 hours. It would be great if we could choose the option “time away” with these conditions. 

Thank you for your great work with this very useful tool! It’s the best service report app for service

**Comment by leviFrosty** [comment]
Hi @rrleandro91,

Thanks for writing in and your kind words.

Just so I can understand it right, you're wanting to have specially tagged time for Credits?

If I'm not misunderstand, this can be accomplished with the current features within the app.

Please follow along:

Add Time -> Type -> Custom -> Type "Credit" (or whatever makes most sense to you) -> Add -> (Add 4 hours) -> Submit

![Simulator Screenshot - iPhone SE (3rd generation) - 2024-07-24 at 00 13 30](https://github.com/user-attachments/assets/e177d516-9d69-4c3e-9ecf-7cd4c912a6da)

This will then appear under your Month Summary as a new line item:

<img width="510" alt="image" src="https://github.com/user-attachments/assets/7863c13d-c081-49c8-96c6-d03cfaeb2290">

If you export your time, it will also appear in the notes section.

I hope this helps, please let me know if this resolves your problem.

Best,
Levi

**Comment by rrleandro91** [comment]
Thank you for your reply! Yes, actually, I did this. But when I share my service report, the time is added to the total. For example, I worked for 60 hours in the service and have 36 hours of credit. Instead of listing this separately as a credit, the app adds it to the total and shows 96 hours. Given that we can’t report this time in our service report, it can confuse the brothers.

Here is my service report


Hours: 89
Studies: 7
Notes:
Time away: 36

**Comment by rrleandro91** [comment]
![IMG_0045](https://github.com/user-attachments/assets/4939c0d6-48b4-4893-bf99-95c8a22671bf)

**Comment by leviFrosty** [comment]
@rrleandro91 

Do you have some time for a Signal/WhatsApp call? I'm just trying to make sure I'm on the same page as you before I potentially make changes.

My number is: 15023348618

Thanks!
Levi

**Comment by leviFrosty** [comment]
To document the changes:

I will be adding a new feature to the 'Add Time' screen that allows you to opt-out of including a certain tag (label) as part of your exported service report. This way when exporting time it doesn't sum it to the total, but instead lists it under the notes.

Best,
Levi

**Comment by rrleandro91** [comment]
Thank you for your good work! I’m recommending your app to everybody!

Obter o Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Levi Wilkerson ***@***.***>
Enviado: Thursday, July 25, 2024 12:11:54 PM
Para: leviFrosty/jw-time ***@***.***>
Cc: rrleandro91 ***@***.***>; Mention ***@***.***>
Assunto: Re: [leviFrosty/jw-time] [BUG] Time away for special pioneers (Issue #136)


To document the changes:

I will be adding a new feature to the 'Add Time' screen that allows you to opt-out of including a certain tag (label) as part of your exported service report. This way when exporting time it doesn't sum it to the total, but instead lists it under the notes.

Best,
Levi

**Comment by leviFrosty** [comment]
@rrleandro91 

I'm very pleased to let you know that this feature has been implemented as of 9e6af7cc4f6b6d0ee62145f6cc37398304315c4f

I hope you enjoy the update when it's released to the app stores in the coming week.

Thank you again for your patience.

Best,
Levi
