### ISSUE TITLE
[BUG] No Chinese

### ISSUE THREAD

**Issue by DAIANYI77** [leviFrosty/jw-time#146]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior:沒有中文

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. (Draw on images if possible)

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone 15 Pro Max]
- OS: [e.g. iOS 17.1.2]
- Version [e.g. 1.9.0]

**Additional context**

**Comment by leviFrosty** [comment]
嗨@DAIANYI77，

您屬於哪個地區？比如說台灣？中國？別的地方？

您能否向我展示您的裝置使用哪種語言設定的螢幕截圖？

我能夠在我的設備上顯示中文 - 我只需要更多資訊。

謝謝！
列維

如果更方便的話，請隨時透過 Whatsapp 或 Signal 給我發訊息：+15023348618

--- 

Hi @DAIANYI77,

What locale are you part of? For example, Taiwan? China? Somewhere else?

Can you show me a screenshot of which language setting your device uses?

I'm able to get Chinese to display on my device - I just need a little more information.

Thanks!
Levi

Feel free to message me on Whatsapp or Signal if that's easier: +15023348618

**Comment by leviFrosty** [comment]
您好，這已透過更改解決: fa99cef8646a800c8772fc73b917456000f54bc1

預計本週即將發布的版本中會出現這一點。謝謝你的耐心

謝謝，
Levi

--

Hi, this is resolved with change: fa99cef8646a800c8772fc73b917456000f54bc1

Expect this in the coming release this week. Thanks for your patience

Thanks,
Levi
