### ISSUE TITLE
[Question] Correction for time

### ISSUE THREAD

**Issue by gabgrenier8** [leviFrosty/JW-Time#85]
Hi How can I make a correction to a time that i enter or to erase a time data for a given date? 

Ty

**Comment by leviFrosty** [comment]
Hi, thanks for reaching out.

Currently there are no ways to edit time entries, as they are easy enough to delete -> add a new one.

So to delete a time entry, swipe from the right on it. This also applies to almost all user-entered information as well.

Contacts, conversations, and time entries can all be deleted this way.

![image](https://github.com/leviFrosty/JW-Time/assets/79994715/83202ed1-ea94-4cf2-980b-adf01e6b41e0)

I plan on making a tutorial feature in the future for some of these basic actions so it is more clear for new users.

Let me know if this resolves your issue.

All the best,
Levi

**Comment by leviFrosty** [comment]
@gabgrenier8 I'm not sure if my previous message was received by you, so I made sure to ping you in this one.

Please let me know if the above resolves your problem.

Thank you,
Levi

**Comment by leviFrosty** [comment]
As part of release 1.21.1, the app will now hint to you how to delete time entries.

Thank you,
Levi

**Comment by gabgrenier8** [comment]
Yes sorry    . Thank you

Le lun. 5 févr. 2024 à 12:38, Levi Wilkerson ***@***.***> a
écrit :
