### ISSUE TITLE
[BUG] Monthly Report Calculation Not Clear

### ISSUE THREAD

**Issue by CampHeber** [leviFrosty/JW-Time#86]
Good evening, I have an issue with the app. I have 23 hours of service and 24 of LDC (23+24=47), but the app is showing a total of 48 hours.

I would also like that in a future update, it provides a summary in hours and minutes since currently only hours are shown. I can't determine the total minutes, and any remaining minutes do not carry over to the next month.

Thank you very much for creating this app

- Device: IPhone XR 
- OS: [e.g. iOS 17.3]
- Version [1.20.1]
![IMG_2795](https://github.com/leviFrosty/JW-Time/assets/158535046/bd1ca378-e84c-4eff-8539-78f98efed156)

**Comment by leviFrosty** [comment]
Thanks for submitting this bug report.

I have received your issue and will be looking into what may be causing this.

In regards to wanting to see minutes on your time report: I think that would be a good idea. I will try to see in what way we can implement this in an elegant way.

Thanks!
Levi

**Comment by leviFrosty** [comment]
Just want to let you know that I can replicate your issue and have identified the problem.

I am currently working a fix. I will update you once this issue has been resolved.

Thanks again,
Levi

**Comment by leviFrosty** [comment]
A fixed has implemented with 94e1eac39d83fac630656f3272894ee5cc701d3e and this will be pushed in the next future release.

It resolves both the "inaccuracy" that you were describing as well as the ability to view partial hours.

I will likely publish this sometime in the coming days - thank you for reaching out!

**Comment by leviFrosty** [comment]
@CampHeber I'm not sure if you have received any notifications from my messages so far, so I will ping you in case it was missed.

Thank you again!
Levi

**Comment by CampHeber** [comment]
Thank you for your attention, and again, thanks for this excellent application.


Enviado desde Yahoo Mail para iPhone


El viernes, febrero 2, 2024, 1:48 a.m., Levi Wilkerson ***@***.***> escribió:




A fixed has implemented with 94e1eac and this will be pushed in the next future release.

It resolves both the "inaccuracy" that you were describing as well as the ability to view partial hours.

I will likely publish this sometime in the coming days - thank you for reaching out!
