### ISSUE TITLE
[Question] How To View Remaining Hours

### ISSUE THREAD

**Issue by KarenEG** [leviFrosty/JW-Time#90]
First of all, I am really enjoying this app. I especially love the geotag feature for return visits! So coo! 

One feature I did like from the app I used right before yours is that it would tell me if I was behind on schedule or  ahead of my goal for the month. Is there a way to do this in your app? 

Here is a picture in case I’m not explaining myself clearly:
![IMG_1484](https://github.com/leviFrosty/JW-Time/assets/162097874/28f54a7b-d166-44e3-bbb0-7b2dad5a8dea)
![IMG_1484](https://github.com/leviFrosty/JW-Time/assets/162097874/b5b5fea4-a5f9-4a94-9a0e-58d49f0a7aa4)

Thank you for all your hard work!!! 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by leviFrosty** [comment]
@KarenEG ,

Does this resolve your issue?

Thanks,
Levi

**Comment by leviFrosty** [comment]
@KarenEG,

As you haven't responded to this ticket in over 5 days I will be closing this as I assume this has resolved your request. Feel free to comment back and reopen the ticket.

Thanks!
Levi
