### ISSUE TITLE
[FEATURE] Annual View Month Summary

### ISSUE THREAD

**Issue by jimmypozo** [leviFrosty/JW-Time#92]
Good morning, it is a pleasure to greet you and we send you a big hug.

**Is your feature request related to a problem? Please describe.**
It is not related to a problem

**Describe the solution you'd like**
I like the application and I consider it to be a great help for the Christian ministry. As a suggestion, I think that it lacks a summary of all the months of service since the theocratic year began so we could see in detail how we have served Jehovah in past months.

**Describe alternatives you've considered**
a dedicated tab to view service hours from previous months as a summary. 
Example September 55, October 45, November 51, December 40 
In my opinion, initially showing the total hours would be very helpful

**Additional context**
Thank you very much, Jehovah continue to bless your great work.

**Comment by leviFrosty** [comment]
Hi @jimmypozo!

Thanks for writing in a feature request. As I do think this is be a good idea.

I will be coming up with a solution to this and will eventually implement feature in the near future.

I cannot give you a timeline on how long it will be until this feature is done, but I will keep you in the loop to the best of my ability.

To be clear, you're wanting to see a screen something similar to this? (this screen is merely for reference, ignore what the actual screen says):
<img width="146" alt="image" src="https://github.com/leviFrosty/JW-Time/assets/79994715/dcbbac04-4d8d-4950-8d4e-cf4cbbb80cd4">

Thanks again!
Levi

**Comment by jimmypozo** [comment]
Good night.

Thank you very much for responding to the request, and if a screen like the one in the example would be enough, it would help us precursors a lot to know the hours we have dedicated to the service during the theocratic year and in that way know if I still need.

thanks for the support
________________________________
De: Levi Wilkerson ***@***.***>
Enviado: Friday, March 8, 2024 7:03:20 PM
Para: leviFrosty/JW-Time ***@***.***>
Cc: jimmypozo ***@***.***>; Mention ***@***.***>
Asunto: Re: [leviFrosty/JW-Time] [FEATURE] Annual View Month Summary (Issue #92)


Hi @jimmypozo<https://github.com/jimmypozo>!

Thanks for writing in a feature request. As I do think this is be a good idea.

I will be coming up with a solution to this and will eventually implement feature in the near future.

I cannot give you a timeline on how long it will be until this feature is done, but I will keep you in the loop to the best of my ability.

To be clear, you're wanting to see a screen something similar to this? (this screen is merely for reference, ignore what the actual screen says):
image.png (view on web)<https://github.com/leviFrosty/JW-Time/assets/79994715/dcbbac04-4d8d-4950-8d4e-cf4cbbb80cd4>

Thanks again!
Levi

**Comment by leviFrosty** [comment]
Hi @jimmypozo!

Good news! This feature has been added. See f07bdd9b748c24a92cc1ca73c73039bb76e70fd8

It will be available in the next release, so stay tuned :)

I will close this ticket now. Let me know if you have any questions or concerns after you get your hands on it.

Best,
Levi

**Comment by jimmypozo** [comment]
Good morning

Thank you for your help, and in advance I send you a big hug of gratitude.
I have tried the new update and it is perfect, thank you for your support with this change, we precursors have better control of the service.
Just as a question, have you thought about using notifications?; It would be great if every so often during the month of service, as a notification, the app notifies you how many hours of preaching you need to reach the monthly goal.
I know it must take work to do it, so I only leave you as a concern so that at some point you have thought about it.

Thanks brother

**Comment by jimmypozo** [comment]
Good morning

Thank you for your help, and in advance I send you a big hug of gratitude.
I have tried the new update and it is perfect, thank you for your support with this change, we precursors have better control of the service.
Just as a question, have you thought about using notifications?; It would be great if every so often during the month of service, as a notification, the app notifies you how many hours of preaching you need to reach the monthly goal.
I know it must take work to do it, so I only leave you as a concern so that at some point you have thought about it.

Thanks brother

De: Levi Wilkerson ***@***.***>
Fecha: viernes, 29 de marzo de 2024, 16:02
Para: leviFrosty/JW-Time ***@***.***>
CC: jimmypozo ***@***.***>, Mention ***@***.***>
Asunto: Re: [leviFrosty/JW-Time] [FEATURE] Annual View Month Summary (Issue #92)

Hi @jimmypozo<https://github.com/jimmypozo>!

Good news! This feature has been added. See f07bdd9<https://github.com/leviFrosty/JW-Time/commit/f07bdd9b748c24a92cc1ca73c73039bb76e70fd8>

It will be available in the next release, so stay tuned :)

I will close this ticket now. Let me know if you have any questions or concerns after you get your hands on it.

Best,
Levi

**Comment by leviFrosty** [comment]
@jimmypozo 

Thanks for writing back, glad you enjoy it.

Because I do not want to detract from the significance of the return visit notifications, I do not want to add any additional notifications to the app.

Although this feature might be nice for some, it will likely cause frustration for others.

I hope you understand.

Thank you!
Levi
