### ISSUE TITLE
[FEATURE/BUG] Annual Goal Setting Toggle

### ISSUE THREAD

**Issue by marlonsabala** [leviFrosty/JW-Time#95]
**Describe the bug**
In the monthly report page, the yearly bar should be hidden for special pioneers in my opinion. It does not apply to them. 

What do you think?

**Comment by marlonsabala** [comment]
Hi Levi,

I think that is an excellent solution.
And yes, it does apply to all special pioneers. They have a monthly goal only.

Thanks

**Comment by leviFrosty** [comment]
Hello again @marlonsabala,

96ff8d822a08470d9decf06193a79e21a0c7d8ca and d35f1752a505bbf42cad4d5d57eb87c8f4befd49 adds these changes that we discussed earlier.

You will see this fix and new feature in the next release :)

Thank you for pointing out some improvements that could be made. I will close this ticket now.

Best,
Levi

**Comment by marlonsabala** [comment]
Fantastic stuff. Thanks Levi

Marlon Sabala
