### ISSUE TITLE
[FEATURE] Monthly planner

### ISSUE THREAD

**Issue by flossyk1** [leviFrosty/jw-time#97]
**issue**
having recently moved to iOS, found this app is great, the only thing I miss from a different app I used on android is the ability to plan ahead a schedule of ministry hours in month view as each month my routine is different. This made a big deal to see if I would be close to getting the hours or not 

**solution**
a month view of your ‘scheduled hours’ which is then updated as you fill in entries/ synced with actual report

**Describe alternatives you've considered**
Using my old phone or paper 

**Additional context**
![image](https://github.com/leviFrosty/JW-Time/assets/134451218/2d40d8ca-58ef-459b-b668-ea3c45fe3e26)

**Comment by leviFrosty** [comment]
Hi @flossyk1,

Thanks for writing in! This is a highly requested feature and is currently in the pipeline. 

See related feature request: #96 

Thank you for enjoying the app! You can expect the feature in the near future, in the meantime I'll keep you updated on this feature's progress.

Thanks,
Levi

**Comment by flossyk1** [comment]
Ah great news, sorry for duplicating! And thanks for your efforts, really appreciate the time spent on it~

**Comment by leviFrosty** [comment]
@flossyk1 Hi!

Fantastic news! This feature has been added with fe7be58a6c48d2563d2ef6ee9460f6ad6d95c684

Thanks for taking the time to write in a feature request.
Please be on the lookout for this update in the coming days! I will be closing this ticket now.

When you see the feature on your app - and if this new feature is everything you could have hoped for, please leave a review and share JW Time with your friends :)

Best,
Levi

**Comment by flossyk1** [comment]
> @flossyk1 Hi!
> 
> Fantastic news! This feature has been added with [fe7be58](https://github.com/leviFrosty/jw-time/commit/fe7be58a6c48d2563d2ef6ee9460f6ad6d95c684)
> 
> Thanks for taking the time to write in a feature request. Please be on the lookout for this update in the coming days! I will be closing this ticket now.
> 
> When you see the feature on your app - and if this new feature is everything you could have hoped for, please leave a review and share JW Time with your friends :)
> 
> Best, Levi

looking forwrd to it! Thank you, will do
